name: academy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  freezed: ^2.5.2
  go_router: ^14.1.4
  get_it: ^7.6.7
  injectable: ^2.3.2
  rxdart: ^0.27.7
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  smooth_page_indicator: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  video_player: ^2.8.6

  dio: ^5.4.1
  dio_cache_interceptor: ^3.5.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  concentric_transition: ^1.0.3
  dashed_line: ^0.1.0+3
  shared_preferences: ^2.2.2
  injectable_generator: ^2.4.2
  responsive_sizer: ^3.3.0+1
  percent_indicator: ^4.2.3
  grpc: ^3.2.4
  protobuf: ^3.1.0
  freezed_annotation: ^2.4.1
#  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

